import type { IUser } from '@esri/arcgis-rest-portal';
import type { ItemNodeData } from 'storymaps-gemini';
import { modifyStringWithString } from 'storymaps-utils';
import { Config as BriefingConfig, Data as BriefingData } from '../../../blocks/briefing';
import { Config as CollectionConfig, Data as CollectionData } from '../../../blocks/collection';
import { Data as CollectionCoverData } from '../../../blocks/collection/collection-cover';
import { Config as StoryConfig, Data as StoryData } from '../../../blocks/story';
import { Data as StoryCoverData } from '../../../blocks/storycover';
import { MAX_STORY_TITLE_LENGTH } from '../../../constants';
import { getByline, isTitleAutoGeneratedOrEmpty } from '../ItemDefaults/Item';

export interface CoverModifierOptions {
  /** A string prefix to add to the duplicated item's title (most common use case is `"(Copy) "` with a trailing space). */
  titlePrefix: string;
  /** The string to use for the title if the author never added a title to their cover (e.g., `"Untitled story"`). */
  untitledItemString: string;
  /** The current user, for changing the byline */
  user: IUser;
}

/**
 * Checks if the given node is a root node type.
 * @param node - The node to check.
 * @returns True if the node is a root node type, false otherwise.
 */
export function isRootNodeType(node: ItemNodeData): boolean {
  return node.type === 'story' || node.type === 'collection' || node.type === 'briefing';
}

/**
 * Prepends a modifier to the cover title of an item AND changes the byline to the new item owner (change made because SMX links to owner's profile).
 * If the node type is not 'storycover' or 'collection-cover', the node is returned unchanged.
 * If the title is auto-generated or empty, it is replaced with the `untitledItemString`.
 * The `titlePrefix` is prepended to the original title, and the resulting title is limited to `MAX_STORY_TITLE_LENGTH` characters.
 * @returns The modified item node data.
 */
export function prependModifierToCoverTitleAndChangeByline(
  /** The item node data (JSON Data) */
  node: ItemNodeData,
  options: CoverModifierOptions
): ItemNodeData {
  if (!['storycover', 'collection-cover'].includes(node.type)) {
    return node;
  }
  const blockData = node.data as unknown as StoryCoverData | CollectionCoverData;
  const titleFromData = blockData.title;

  const originalTitle = isTitleAutoGeneratedOrEmpty(titleFromData)
    ? options.untitledItemString
    : titleFromData;
  const coverTitle = modifyStringWithString({
    stringModifier: options.titlePrefix,
    originalString: originalTitle,
    maxLength: MAX_STORY_TITLE_LENGTH,
  });

  const newByline = getByline(options.user.firstName, options.user.lastName);

  return {
    ...node,
    data: {
      ...blockData,
      title: coverTitle,
      byline: newByline,
    },
  };
}

/**
 * Prepends a modifier to the meta title of a story item.
 * @returns The modified item node data.
 */
export function prependModifierToMetaTitle(
  /** The item node data (JSON Data) */
  node: ItemNodeData,
  titlePrefix: CoverModifierOptions['titlePrefix']
): ItemNodeData {
  if (!isRootNodeType) {
    return node;
  }
  const blockData = node.data as unknown as StoryData | BriefingData | CollectionData;

  if (!blockData.metaSettings || typeof blockData.metaSettings.title !== 'string') {
    return node;
  }

  const metaSettings = structuredClone(blockData.metaSettings);
  metaSettings.title = modifyStringWithString({
    stringModifier: titlePrefix,
    originalString: blockData.metaSettings.title,
    maxLength: MAX_STORY_TITLE_LENGTH,
  });

  return {
    ...node,
    data: {
      ...blockData,
      metaSettings,
    },
  };
}

/**
 * Discards author analytics from the given ItemNodeData.
 * @param node - The ItemNodeData to modify.
 * @returns The modified ItemNodeData with author analytics discarded.
 */
export function discardAuthorAnalytics(node: ItemNodeData): ItemNodeData {
  if (!isRootNodeType) {
    return node;
  }

  const blockConfig = node.config as unknown as StoryConfig | BriefingConfig | CollectionConfig;

  if (!blockConfig?.analytics) {
    return node;
  }

  const config = structuredClone(blockConfig);
  delete config.analytics;

  return {
    ...node,
    config,
  };
}
